<?php

/**
 * This file is part of the Cubiche/Metadata component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Core\Metadata\Tests\Units\Driver;

use Cubiche\Core\Metadata\Tests\Units\TestCase;

/**
 * AbstractYamlDriverTests class.
 *
 * Generated by TestGenerator on 2016-11-01 at 12:47:41.
 */
class AbstractYamlDriverTests extends TestCase
{
    /**
     * Test class.
     */
    public function testClass()
    {
        $this
            ->testedClass
                ->isAbstract()
        ;
    }
}
