<?php

/**
 * This file is part of the Cubiche/Metadata component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Core\Metadata\Tests\Units\Driver;

use Cubiche\Core\Metadata\Tests\Units\TestCase;

/**
 * DriverFactoryTests class.
 *
 * Generated by TestGenerator on 2016-11-01 at 12:47:41.
 */
class DriverFactoryTests extends TestCase
{
    /**
     * Test RegisterAnnotationDriver method.
     */
    public function testRegisterAnnotationDriver()
    {
        // todo: Implement testRegisterAnnotationDriver().
    }

    /**
     * Test RegisterYamlDriver method.
     */
    public function testRegisterYamlDriver()
    {
        // todo: Implement testRegisterYamlDriver().
    }

    /**
     * Test RegisterXmlDriver method.
     */
    public function testRegisterXmlDriver()
    {
        // todo: Implement testRegisterXmlDriver().
    }

    /**
     * Test CreateAnnotationDriver method.
     */
    public function testCreateAnnotationDriver()
    {
        // todo: Implement testCreateAnnotationDriver().
    }

    /**
     * Test CreateYamlDriver method.
     */
    public function testCreateYamlDriver()
    {
        // todo: Implement testCreateYamlDriver().
    }

    /**
     * Test CreateXmlDriver method.
     */
    public function testCreateXmlDriver()
    {
        // todo: Implement testCreateXmlDriver().
    }

    /**
     * Test Instance method.
     */
    public function testInstance()
    {
        // todo: Implement testInstance().
    }
}
