<?php

/**
 * This file is part of the Cubiche/Metadata component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Core\Metadata\Tests\Units\Driver;

use Cubiche\Core\Metadata\Driver\AbstractXmlDriver;
use Cubiche\Core\Metadata\Tests\Units\TestCase;

/**
 * XmlDriverTestCase class.
 *
 * Generated by TestGenerator on 2016-11-01 at 12:47:41.
 */
abstract class XmlDriverTestCase extends TestCase
{
    /**
     * @param array $paths
     *
     * @return AbstractXmlDriver
     */
    abstract protected function createXmlDriver(array $paths = []);

    /**
     * Test extractElementAttributes method.
     */
    public function testExtractElementAttributes()
    {
        $this
            ->given($driver = $this->createXmlDriver())
            ->then()
                ->object($driver)
                    ->isInstanceOf(AbstractXmlDriver::class)
        ;
    }

    /**
     * Test getMapping method.
     */
    public function testGetMapping()
    {
        $this
            ->given($driver = $this->createXmlDriver())
            ->then()
                ->object($driver)
                    ->isInstanceOf(AbstractXmlDriver::class)
        ;
    }
}
