<?php

/**
 * This file is part of the Cubiche/Metadata component.
 *
 * Copyright (c) Cubiche
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cubiche\Core\Metadata\Tests\Units\Exception;

use Cubiche\Core\Metadata\Tests\Units\TestCase;

/**
 * MappingExceptionTests class.
 *
 * Generated by TestGenerator on 2016-11-01 at 12:47:41.
 */
class MappingExceptionTests extends TestCase
{
    /**
     * Test PathRequired method.
     */
    public function testPathRequired()
    {
        // todo: Implement testPathRequired().
    }

    /**
     * Test InvalidDirectory method.
     */
    public function testInvalidDirectory()
    {
        // todo: Implement testInvalidDirectory().
    }
}
